/* ==========================================================================
   DADOS DO QUIZ - AULA 2.3
   Inclua este arquivo no HTML da Aula 2.3 ANTES de js/main.js:
     <script src="js/aula2.3.js"></script>
     <script src="js/main.js"></script>
   ========================================================================== */

window.EDUFLEX_QUIZ_QUESTIONS = [
  {
    q: "Sobre os dados geoespaciais e o sensoriamento remoto, assinale a alternativa incorreta:",
    opts: [
      { letter: "A", text: "Os dados geoespaciais são informações associadas a uma localização no espaço geográfico e podem ser representados por pontos, linhas e polígonos em Sistemas de Informação Geográfica.", correct: false, exp: "O sensoriamento remoto não substitui os dados epidemiológicos, os registros dos sistemas de informação em saúde ou as informações obtidas em campo. As imagens de satélite e os demais produtos geoespaciais fornecem informações sobre o contexto ambiental e territorial, enquanto os dados epidemiológicos descrevem a ocorrência e as características dos eventos de saúde. A integração dessas fontes fortalece a identificação de riscos, o monitoramento territorial, o planejamento das ações e a tomada de decisão." },
      { letter: "B", text: "O sensoriamento remoto permite obter informações sobre a superfície terrestre sem contato direto, utilizando sensores que registram a radiação eletromagnética refletida ou emitida pelos alvos.", correct: false, exp: "O sensoriamento remoto não substitui os dados epidemiológicos, os registros dos sistemas de informação em saúde ou as informações obtidas em campo. As imagens de satélite e os demais produtos geoespaciais fornecem informações sobre o contexto ambiental e territorial, enquanto os dados epidemiológicos descrevem a ocorrência e as características dos eventos de saúde. A integração dessas fontes fortalece a identificação de riscos, o monitoramento territorial, o planejamento das ações e a tomada de decisão." },
      { letter: "C", text: "As imagens de satélite utilizadas no sensoriamento remoto podem conter informações além do espectro visível, como o infravermelho e o termal, ampliando as possibilidades de análise ambiental e territorial.", correct: false, exp: "O sensoriamento remoto não substitui os dados epidemiológicos, os registros dos sistemas de informação em saúde ou as informações obtidas em campo. As imagens de satélite e os demais produtos geoespaciais fornecem informações sobre o contexto ambiental e territorial, enquanto os dados epidemiológicos descrevem a ocorrência e as características dos eventos de saúde. A integração dessas fontes fortalece a identificação de riscos, o monitoramento territorial, o planejamento das ações e a tomada de decisão." },
      { letter: "D", text: "O uso integrado de dados de sensoriamento remoto e dados de vigilância em saúde permite identificar padrões espaciais, apoiar o planejamento territorial e fortalecer estratégias de vigilância antecipatória.", correct: false, exp: "O sensoriamento remoto não substitui os dados epidemiológicos, os registros dos sistemas de informação em saúde ou as informações obtidas em campo. As imagens de satélite e os demais produtos geoespaciais fornecem informações sobre o contexto ambiental e territorial, enquanto os dados epidemiológicos descrevem a ocorrência e as características dos eventos de saúde. A integração dessas fontes fortalece a identificação de riscos, o monitoramento territorial, o planejamento das ações e a tomada de decisão." },
      { letter: "E", text: "O sensoriamento remoto substitui os dados epidemiológicos e os sistemas de informação em saúde, tornando desnecessária a coleta de dados em campo e os registros administrativos.", correct: true, exp: "O sensoriamento remoto amplia a capacidade de observar e analisar o território, fornecendo informações sobre aspectos ambientais, climáticos e espaciais. Entretanto, ele não substitui os dados epidemiológicos, os sistemas de informação em saúde, os registros administrativos nem a coleta de dados em campo. Essas diferentes fontes devem ser utilizadas de maneira complementar e integrada, permitindo relacionar a ocorrência dos eventos de saúde às características do território e apoiar decisões mais qualificadas na vigilância em saúde." }
    ]
  }
];